package server

import (
	"github.com/gin-gonic/gin"
	"github.com/goshlanguage/cardsagainstkubernetes/pkg/autogenerated"
)

type GameServerImpl struct {
	State map[string]interface{}
}

// AddGame
func (g *GameServerImpl) AddGame(c *gin.Context) {
	// generate 4 letter game code

	// parse player

	// setup game state

	// add player

	// setup decks
	c.JSON(200, gin.H{
		"empty": "message",
	})
}

// DeleteGame
func (g *GameServerImpl) DeleteGame(c *gin.Context, id string) {
	// remove the key in the global state

	c.JSON(200, gin.H{
		"empty": "message",
	})
}

// FindGameByID
func (g *GameServerImpl) FindGameByID(c *gin.Context, id string) {
	// find the key in the global state and return it

	c.JSON(200, gin.H{
		"empty": "message",
	})
}

// FindGames
func (g *GameServerImpl) FindGames(c *gin.Context, params autogenerated.FindGamesParams) {
	// return the global state, what could go wrong

	c.JSON(200, gin.H{
		"empty": "message",
	})
}

